wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8282:80
  volumes:
  - /var/www/html/docwp/src:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: test123
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: test123    
  